package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.Decision;
import java.util.List;

public interface DecisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision
     *
     * @mbg.generated
     */
    int insert(Decision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision
     *
     * @mbg.generated
     */
    Decision selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision
     *
     * @mbg.generated
     */
    List<Decision> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Decision record);
}