package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.DecisionTransition;
import java.util.List;

public interface DecisionTransitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    int insert(DecisionTransition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    DecisionTransition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    List<DecisionTransition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecisionTransition record);
}