package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.DecisionModel;
import java.util.List;

public interface DecisionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_model
     *
     * @mbg.generated
     */
    int insert(DecisionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_model
     *
     * @mbg.generated
     */
    DecisionModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_model
     *
     * @mbg.generated
     */
    List<DecisionModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecisionModel record);
}