package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.DecisionTransitionSnapshot;
import java.util.List;

public interface DecisionTransitionSnapshotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    int insert(DecisionTransitionSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    DecisionTransitionSnapshot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    List<DecisionTransitionSnapshot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecisionTransitionSnapshot record);
}