package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.RuleSet;
import java.util.List;

public interface RuleSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set
     *
     * @mbg.generated
     */
    int insert(RuleSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set
     *
     * @mbg.generated
     */
    RuleSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set
     *
     * @mbg.generated
     */
    List<RuleSet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RuleSet record);
}