package com.github.eriksen.hello_easy_rules.mapper;

import com.github.eriksen.hello_easy_rules.model.Rule;
import java.util.List;

public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbg.generated
     */
    int insert(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbg.generated
     */
    Rule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbg.generated
     */
    List<Rule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rule record);
}