package com.github.eriksen.hello_easy_rules.model;

import java.io.Serializable;
import java.util.Date;

public class DecisionTransitionSnapshot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.decision
     *
     * @mbg.generated
     */
    private Integer decision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.decision_model
     *
     * @mbg.generated
     */
    private Integer decisionModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.transition
     *
     * @mbg.generated
     */
    private Integer transition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.rule_set_snapshot
     *
     * @mbg.generated
     */
    private Integer ruleSetSnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition_snapshot.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    public DecisionTransitionSnapshot(Integer id, Integer decision, Integer decisionModel, Integer transition, String name, String code, String content, Integer ruleSetSnapshot, String desc, Date createTime) {
        this.id = id;
        this.decision = decision;
        this.decisionModel = decisionModel;
        this.transition = transition;
        this.name = name;
        this.code = code;
        this.content = content;
        this.ruleSetSnapshot = ruleSetSnapshot;
        this.desc = desc;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition_snapshot
     *
     * @mbg.generated
     */
    public DecisionTransitionSnapshot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.id
     *
     * @return the value of sys_decision_transition_snapshot.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.id
     *
     * @param id the value for sys_decision_transition_snapshot.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.decision
     *
     * @return the value of sys_decision_transition_snapshot.decision
     *
     * @mbg.generated
     */
    public Integer getDecision() {
        return decision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.decision
     *
     * @param decision the value for sys_decision_transition_snapshot.decision
     *
     * @mbg.generated
     */
    public void setDecision(Integer decision) {
        this.decision = decision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.decision_model
     *
     * @return the value of sys_decision_transition_snapshot.decision_model
     *
     * @mbg.generated
     */
    public Integer getDecisionModel() {
        return decisionModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.decision_model
     *
     * @param decisionModel the value for sys_decision_transition_snapshot.decision_model
     *
     * @mbg.generated
     */
    public void setDecisionModel(Integer decisionModel) {
        this.decisionModel = decisionModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.transition
     *
     * @return the value of sys_decision_transition_snapshot.transition
     *
     * @mbg.generated
     */
    public Integer getTransition() {
        return transition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.transition
     *
     * @param transition the value for sys_decision_transition_snapshot.transition
     *
     * @mbg.generated
     */
    public void setTransition(Integer transition) {
        this.transition = transition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.name
     *
     * @return the value of sys_decision_transition_snapshot.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.name
     *
     * @param name the value for sys_decision_transition_snapshot.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.code
     *
     * @return the value of sys_decision_transition_snapshot.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.code
     *
     * @param code the value for sys_decision_transition_snapshot.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.content
     *
     * @return the value of sys_decision_transition_snapshot.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.content
     *
     * @param content the value for sys_decision_transition_snapshot.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.rule_set_snapshot
     *
     * @return the value of sys_decision_transition_snapshot.rule_set_snapshot
     *
     * @mbg.generated
     */
    public Integer getRuleSetSnapshot() {
        return ruleSetSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.rule_set_snapshot
     *
     * @param ruleSetSnapshot the value for sys_decision_transition_snapshot.rule_set_snapshot
     *
     * @mbg.generated
     */
    public void setRuleSetSnapshot(Integer ruleSetSnapshot) {
        this.ruleSetSnapshot = ruleSetSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.desc
     *
     * @return the value of sys_decision_transition_snapshot.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.desc
     *
     * @param desc the value for sys_decision_transition_snapshot.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition_snapshot.createTime
     *
     * @return the value of sys_decision_transition_snapshot.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition_snapshot.createTime
     *
     * @param createTime the value for sys_decision_transition_snapshot.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}