package com.github.eriksen.hello_easy_rules.model;

import java.io.Serializable;
import java.util.Date;

public class DecisionTransition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.rule_set
     *
     * @mbg.generated
     */
    private Integer ruleSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.enable
     *
     * @mbg.generated
     */
    private Integer enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_decision_transition.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    public DecisionTransition(Integer id, String code, String name, String content, Integer ruleSet, String desc, Integer enable, Date createTime, Date updateTime) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.content = content;
        this.ruleSet = ruleSet;
        this.desc = desc;
        this.enable = enable;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_decision_transition
     *
     * @mbg.generated
     */
    public DecisionTransition() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.id
     *
     * @return the value of sys_decision_transition.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.id
     *
     * @param id the value for sys_decision_transition.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.code
     *
     * @return the value of sys_decision_transition.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.code
     *
     * @param code the value for sys_decision_transition.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.name
     *
     * @return the value of sys_decision_transition.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.name
     *
     * @param name the value for sys_decision_transition.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.content
     *
     * @return the value of sys_decision_transition.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.content
     *
     * @param content the value for sys_decision_transition.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.rule_set
     *
     * @return the value of sys_decision_transition.rule_set
     *
     * @mbg.generated
     */
    public Integer getRuleSet() {
        return ruleSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.rule_set
     *
     * @param ruleSet the value for sys_decision_transition.rule_set
     *
     * @mbg.generated
     */
    public void setRuleSet(Integer ruleSet) {
        this.ruleSet = ruleSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.desc
     *
     * @return the value of sys_decision_transition.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.desc
     *
     * @param desc the value for sys_decision_transition.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.enable
     *
     * @return the value of sys_decision_transition.enable
     *
     * @mbg.generated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.enable
     *
     * @param enable the value for sys_decision_transition.enable
     *
     * @mbg.generated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.createTime
     *
     * @return the value of sys_decision_transition.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.createTime
     *
     * @param createTime the value for sys_decision_transition.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_decision_transition.updateTime
     *
     * @return the value of sys_decision_transition.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_decision_transition.updateTime
     *
     * @param updateTime the value for sys_decision_transition.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}