package com.github.eriksen.hello_easy_rules.model;

import java.io.Serializable;
import java.util.Date;

public class RuleSetConnect implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.rule_set
     *
     * @mbg.generated
     */
    private Integer ruleSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_set_snapshot.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_rule_set_snapshot
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set_snapshot
     *
     * @mbg.generated
     */
    public RuleSetConnect(Integer id, Integer ruleSet, String name, String desc, String content, Date createTime) {
        this.id = id;
        this.ruleSet = ruleSet;
        this.name = name;
        this.desc = desc;
        this.content = content;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_set_snapshot
     *
     * @mbg.generated
     */
    public RuleSetConnect() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.id
     *
     * @return the value of sys_rule_set_snapshot.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.id
     *
     * @param id the value for sys_rule_set_snapshot.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.rule_set
     *
     * @return the value of sys_rule_set_snapshot.rule_set
     *
     * @mbg.generated
     */
    public Integer getRuleSet() {
        return ruleSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.rule_set
     *
     * @param ruleSet the value for sys_rule_set_snapshot.rule_set
     *
     * @mbg.generated
     */
    public void setRuleSet(Integer ruleSet) {
        this.ruleSet = ruleSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.name
     *
     * @return the value of sys_rule_set_snapshot.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.name
     *
     * @param name the value for sys_rule_set_snapshot.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.desc
     *
     * @return the value of sys_rule_set_snapshot.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.desc
     *
     * @param desc the value for sys_rule_set_snapshot.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.content
     *
     * @return the value of sys_rule_set_snapshot.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.content
     *
     * @param content the value for sys_rule_set_snapshot.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_set_snapshot.createTime
     *
     * @return the value of sys_rule_set_snapshot.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_set_snapshot.createTime
     *
     * @param createTime the value for sys_rule_set_snapshot.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}